// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/pdcgo/order_service"
	"github.com/pdcgo/shared/configs"
	"github.com/pdcgo/shared/custom_connect"
	"net/http"
)

// Injectors from wire.go:

func InitializeApp() (App, error) {
	serveMux := http.NewServeMux()
	appConfig, err := configs.NewProductionConfig()
	if err != nil {
		return nil, err
	}
	db, err := NewDatabase(appConfig)
	if err != nil {
		return nil, err
	}
	cache, err := NewCache(appConfig)
	if err != nil {
		return nil, err
	}
	authorization := NewAuthorization(appConfig, db, cache)
	defaultClientInterceptor, err := custom_connect.NewDefaultClientInterceptor()
	if err != nil {
		return nil, err
	}
	trackingServiceClient := NewTrackingServiceClient(appConfig, defaultClientInterceptor)
	defaultInterceptor, err := custom_connect.NewDefaultInterceptor()
	if err != nil {
		return nil, err
	}
	revenueServiceClient := NewRevenueServiceClient(appConfig, defaultClientInterceptor)
	registerHandler := order_service.NewRegister(serveMux, db, authorization, trackingServiceClient, defaultInterceptor, revenueServiceClient)
	registerReflectFunc := custom_connect.NewRegisterReflect(serveMux)
	apiFunc := NewApi(serveMux, registerHandler, registerReflectFunc)
	createTokenFromUsername := NewCreateTokenFromUsername(db, appConfig)
	setAuthorization := NewSetAuthorization(createTokenFromUsername, appConfig)
	helper := NewHelper(createTokenFromUsername, setAuthorization)
	orderShippedFunc := NewOrderShipped(db, appConfig, defaultClientInterceptor, helper)
	app := NewApp(apiFunc, orderShippedFunc)
	return app, nil
}
